spring.application.name=enterprise-ai-document-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/eadp
spring.datasource.username=eadp_user
spring.datasource.password=eadp_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true